package com.example.util

object SalonStrings {
    fun get(arg1: String, arg2: String): String {
        val (key, lang) = if (arg1.equals("hi", true) || arg1.equals("en", true)) {
            arg2 to arg1
        } else {
            arg1 to arg2
        }
        val isHindi = lang.equals("hi", ignoreCase = true)
        return if (isHindi) hindiStrings[key] ?: englishStrings[key] ?: key
        else englishStrings[key] ?: key
    }


    private val englishStrings = mapOf(
        // Salon settings screens
        "account_holder_label" to "Account Holder Name",
        "active" to "Active",
        "add_category_title" to "Add Category",
        "add_combo_title" to "Add Package",
        "add_service_title" to "Add Service",
        "add_staff_title" to "Add Stylist",
        "all_staff_assigned" to "All stylists",
        "assign_staff_title" to "Stylists who do this service",
        "booking_settings_subtitle" to "Control how customers can book",
        "booking_settings_title" to "Booking Settings",
        "booking_window_hint" to "How many days ahead customers can book (max 30)",
        "btn_save" to "Save",
        "cancel" to "Cancel",
        "categories_count" to "categories",
        "categories_title" to "Categories",
        "category_sort_order_label" to "Display order",
        "combo_total_duration" to "Total time",
        "combos_subtitle" to "Bundle services at a special price",
        "delete" to "Delete",
        "edit_category_title" to "Edit Category",
        "edit_combo_title" to "Edit Package",
        "ifsc_label" to "Bank IFSC Code",
        "inactive" to "Inactive",
        "manage_staff_hours_services" to "Working hours & services",
        "min_notice_hint" to "Minimum time between booking and appointment",
        "minutes_abbr" to "min",
        "payout_subtitle" to "Where your earnings are paid",
        "save" to "Save",
        "save_booking_settings" to "Save Booking Settings",
        "save_payout_details" to "Save Payout Details",
        "save_salon_hours" to "Save Salon Hours",
        "save_staff_hours" to "Save Working Hours",
        "save_staff_services" to "Save Services",
        "section_booking_settings" to "Booking Settings",
        "section_booking_settings_desc" to "Slot gap, advance booking, late policy",
        "section_combos" to "Packages",
        "section_combos_desc" to "Combine services into offers",
        "section_payout_details" to "Payout Details",
        "section_payout_details_desc" to "UPI or bank account for payments",
        "section_salon_profile" to "Salon Profile",
        "section_salon_profile_desc" to "Name, address, photos",
        "section_services" to "Services",
        "section_services_desc" to "Services, prices and duration",
        "section_staff" to "Staff",
        "section_staff_desc" to "Stylists, hours and commission",
        "section_time_off" to "Breaks & Leave",
        "section_time_off_desc" to "Lunch breaks, holidays and staff leave",
        "section_working_hours" to "Working Hours",
        "section_working_hours_desc" to "Opening and closing time for each day",
        "service_duration_hint" to "How long the service takes (customers see slots for this length)",
        "services_catalog_title" to "Services",
        "services_count" to "services",
        "slot_interval_hint" to "Gap between start times shown to customers. Customers also get a slot as soon as a stylist becomes free.",
        "staff_assigned_count" to "stylists",
        "staff_commission_suffix" to "commission",
        "staff_members_count" to "stylists",
        "staff_tab_hours" to "Working Hours",
        "staff_tab_services" to "Services",
        "staff_title" to "Staff",
        "working_hours_subtitle" to "Customers can only book inside these hours",
        "working_hours_title" to "Salon Working Hours",
        "zero_wait_desc" to "Customers are notified automatically if you run late, and get credit if the delay crosses your limit.",
        "app_title" to "Salon Owner",
        "login_title" to "Salon Owner Login",
        "login_subtitle" to "Sign in to manage your salon, bookings & team",
        "email_label" to "Email Address",
        "email_placeholder" to "name@example.com",
        "password_label" to "Password",
        "confirm_password_label" to "Confirm Password",
        "login_btn" to "Login",
        "signup_btn" to "Create Account",
        "need_account" to "Don't have an account? Sign up",
        "have_account" to "Already have an account? Login",
        "signup_title" to "Register as Salon Owner",
        "signup_subtitle" to "Create your account to start managing your salon",

        // Steps
        "step_owner" to "Owner Details",
        "step_salon" to "Salon Details",
        "step_verify" to "Verification",
        "step_1_of_3" to "Step 1 of 3",
        "step_2_of_3" to "Step 2 of 3",
        "step_3_of_3" to "Step 3 of 3",

        // Step 1
        "owner_name_label" to "Owner Full Name",
        "owner_name_hint" to "Enter your full name",
        "language_preference" to "Preferred Language",
        "language_english" to "English",
        "language_hindi" to "हिंदी (Hindi)",
        "next_btn" to "Continue",
        "back_btn" to "Back",

        // Step 2
        "salon_name_label" to "Salon Name",
        "salon_name_hint" to "e.g. Looks Unisex Salon",
        "salon_type_label" to "Salon Type",
        "type_men" to "Men",
        "type_women" to "Women",
        "type_unisex" to "Unisex",
        "address_label" to "Full Address",
        "address_hint" to "Shop / Building / Street address",
        "area_label" to "Area / Locality",
        "area_hint" to "e.g. Bandra West, MG Road",
        "city_label" to "City",
        "city_hint" to "e.g. Mumbai, Delhi, Bengaluru",
        "pincode_label" to "Pincode",
        "pincode_hint" to "6-digit pincode (e.g. 400050)",
        "phone_label" to "Salon Contact Phone",
        "phone_hint" to "10-digit mobile number",
        "location_header" to "Map Location (Optional)",
        "use_my_location" to "Use My Current Location",
        "lat_label" to "Latitude",
        "lng_label" to "Longitude",
        "gst_label" to "GST Number (Optional)",
        "gst_hint" to "15-digit GSTIN (e.g. 27AAAAA0000A1Z5)",

        // Step 3
        "verify_header" to "Document Verification",
        "verify_sub" to "Upload at least one valid business or identity document (Max 5MB)",
        "doc_type_label" to "Document Type",
        "doc_gst" to "GST Certificate",
        "doc_shop_license" to "Shop & Establishment License",
        "doc_visiting_card" to "Visiting Card",
        "doc_id_proof" to "Owner ID Proof (Aadhaar / PAN)",
        "doc_other" to "Other Official Document",
        "select_file" to "Select Document (Image or PDF)",
        "file_selected" to "Selected file:",
        "terms_checkbox" to "I accept the Terms & Conditions and declare that all details provided are accurate.",
        "submit_verification" to "Submit for Verification",

        // Pending & Rejected
        "pending_title" to "Salon Under Review",
        "pending_desc" to "Your salon is under review. We'll notify you once approved.",
        "refresh_status" to "Refresh Status",
        "rejected_title" to "Application Rejected",
        "rejection_reason_label" to "Reason for Rejection:",
        "edit_resubmit" to "Edit and Resubmit",
        "sign_out" to "Sign Out",

        // Part 2: 4 Bottom Tabs
        "tab_today" to "Aaj / Today",
        "tab_bookings" to "Bookings",
        "tab_salon" to "Salon",
        "tab_earnings" to "Kamai / Earnings",

        // Dashboard Stats
        "stat_today_bookings" to "Today's Bookings",
        "stat_completed" to "Completed",
        "stat_upcoming" to "Upcoming",
        "stat_revenue" to "Revenue",
        "stat_no_shows" to "No-shows",
        "stat_pending_replies" to "Pending Review Replies",
        "salon_off_banner" to "Your salon is currently OFF for customers",
        "salon_is_active_online" to "Salon is OPEN & accepting bookings",
        "salon_turn_on" to "Turn ON",
        "salon_turn_off" to "Turn OFF",
        "btn_add_walkin" to "+ Add Walk-in",
        "btn_view_schedule" to "View Today's Schedule",
        "quick_actions" to "Quick Actions",
        "dashboard_title" to "Today's Overview",
        "live_sync_active" to "Live Realtime Sync",

        // Today's Schedule
        "schedule_title" to "Today's Schedule",
        "all_stylists" to "All Stylists",
        "btn_arrived" to "Arrived",
        "btn_cancel" to "Cancel",
        "btn_noshow" to "No-show",
        "btn_start_service" to "Start Service",
        "btn_mark_done" to "Mark Done",
        "empty_bookings" to "No bookings today",
        "empty_bookings_desc" to "You have no bookings scheduled for today yet.",
        "status_confirmed" to "Confirmed",
        "status_arrived" to "Arrived",
        "status_in_service" to "In Service",
        "status_completed" to "Completed",
        "status_cancelled" to "Cancelled",
        "status_no_show" to "No-show",
        "source_walkin" to "Walk-in",
        "source_online" to "Online",
        "tap_to_call" to "Call Customer",

        // Walk-in Modal
        "modal_walkin_title" to "Add Walk-in Booking",
        "modal_walkin_sub" to "Quickly reserve a slot for a walk-in customer",
        "field_stylist" to "Select Stylist",
        "field_service" to "Select Service",
        "field_customer_name" to "Customer Name",
        "field_customer_name_hint" to "Enter customer name",
        "field_customer_phone" to "Customer Phone (Optional)",
        "field_customer_phone_hint" to "10-digit mobile number",
        "btn_create_walkin" to "Create Walk-in Booking",
        "btn_close" to "Close",

        // Notifications
        "notifications_title" to "Notifications",
        "no_notifications" to "No new alerts",

        // Legacy / Shared
        "verified_badge" to "Verified Partner",
        "status_approved" to "Approved",
        "hours_note" to "Operating hours: 10:00 AM – 8:00 PM (All 7 days)",

        // Part 3: Bookings List, Customer History, Reschedule & Time Off
        "subtab_upcoming" to "Upcoming",
        "subtab_past" to "Past",
        "header_today" to "Today",
        "header_tomorrow" to "Tomorrow",
        "booking_details_title" to "Booking Details",
        "btn_call_customer" to "Call Customer",
        "btn_whatsapp_customer" to "WhatsApp Customer",
        "btn_view_history" to "View Customer History",
        "btn_reschedule" to "Reschedule",
        "btn_cancel_booking" to "Cancel Booking",
        "reschedule_dialog_title" to "Reschedule Booking",
        "select_new_date" to "Select New Date",
        "select_new_time" to "Select New Time Slot",
        "time_slot_busy" to "Stylist is booked at this time",
        "confirm_reschedule_btn" to "Confirm New Slot",
        "cancel_booking_confirm_title" to "Cancel Booking?",
        "cancel_booking_confirm_desc" to "Are you sure you want to cancel this booking? The customer will be notified.",
        "confirm_cancel_action" to "Yes, Cancel",
        "customer_history_title" to "Customer History",
        "customer_total_visits" to "Total Visits",
        "customer_no_shows" to "No-shows",
        "customer_total_spent" to "Total Spent",
        "customer_last_visit" to "Last Visit",
        "badge_regular" to "Loyal Regular",
        "badge_attention" to "Frequent No-Show",
        "badge_new" to "New Customer",
        "empty_upcoming" to "No Upcoming Bookings",
        "empty_upcoming_desc" to "You have no confirmed or active upcoming bookings in this window.",
        "empty_past" to "No Past Bookings",
        "empty_past_desc" to "No completed, cancelled or no-show bookings in this period.",
        "time_off_section_title" to "Staff Time Off & Salon Breaks",
        "recurring_breaks_title" to "Daily / Recurring Breaks",
        "staff_time_off_title" to "Staff Leave & Salon Holidays",
        "btn_add_break" to "+ Add Recurring Break",
        "btn_add_time_off" to "+ Add Leave / Holiday",
        "field_break_label" to "Break Label (e.g. Lunch)",
        "field_leave_reason" to "Reason / Note (Optional)",
        "field_day_of_week" to "Day of Week",
        "day_everyday" to "Every Day",
        "whole_salon_option" to "Whole Salon (All Staff)",
        "conflicts_dialog_title" to "Schedule Conflict Detected",
        "conflicts_dialog_desc" to "This time off overlaps with confirmed bookings. Approving will automatically cancel them and notify customers:",
        "btn_cancel_and_proceed" to "Cancel Bookings & Save Leave",
        "delete_confirm_title" to "Remove Entry?",
        "delete_confirm_desc" to "Are you sure you want to remove this break or time-off entry?",
        "btn_delete" to "Delete",

        // Errors & Validation
        "err_fill_all" to "Please fill in all required fields",
        "err_pincode" to "Pincode must be 6 digits starting with 1-9",
        "err_phone" to "Please enter a valid phone number",
        "err_terms" to "Please accept the Terms & Conditions",
        "err_no_doc" to "Please upload at least one document",
        "err_pass_match" to "Passwords do not match",
        "err_pass_short" to "Password must be at least 6 characters",

        // Part 4: Salon Management Sections
        "salon_menu_title" to "Salon Management",
        "salon_menu_subtitle" to "Configure your profile, services, staff, timings & settings",
        "menu_salon_profile" to "Salon Profile",
        "desc_salon_profile" to "Name, address, photos, contact & active status",
        "menu_services_categories" to "Services & Categories",
        "desc_services_categories" to "Service catalog, pricing, fixed durations & staff",
        "menu_combos_packages" to "Combos & Packages",
        "desc_combos_packages" to "Bundled package deals with special pricing",
        "menu_staff" to "Staff & Stylists",
        "desc_staff" to "Stylists, commission rates, working hours & services",
        "menu_working_hours" to "Working Hours",
        "desc_working_hours" to "Weekly salon open & close timings (Mon - Sun)",
        "menu_time_off" to "Time Off & Breaks",
        "desc_time_off" to "Staff leaves, holidays and daily salon breaks",
        "menu_booking_settings" to "Booking Settings",
        "desc_booking_settings" to "Slot interval, booking window & late arrival credit",
        "menu_payout_details" to "Payout Details",
        "desc_payout_details" to "Bank account & UPI for online settlements",

        // Part 4: Profile Section
        "profile_edit_title" to "Edit Salon Profile",
        "profile_description_label" to "Salon Description",
        "profile_description_hint" to "Tell customers about your salon ambiance, hygiene & specialties",
        "profile_photos_title" to "Salon Showcase Photos",
        "profile_photos_desc" to "Upload showcase photos for your salon. Select one as cover photo.",
        "btn_add_photo" to "+ Add Photo",
        "badge_cover_photo" to "Cover Photo",
        "btn_set_cover" to "Set as Cover",
        "btn_remove_photo" to "Remove",
        "salon_status_toggle" to "Accept Bookings (Salon Active)",
        "salon_status_toggle_desc" to "When switched off, customers cannot view your salon or book slots.",
        "verified_partner_badge" to "Verified Partner",
        "under_review_badge" to "Verification Pending",
        "rating_label" to "Rating",
        "reviews_count" to "reviews",
        "btn_save_profile" to "Save Profile Changes",
        "profile_saved_success" to "Salon profile updated successfully!",

        // Part 4: Services & Categories
        "categories_header" to "Service Categories",
        "btn_add_category" to "+ Add Category",
        "category_name_label" to "Category Name",
        "category_name_hint" to "e.g. Haircuts, Skin & Spa, Grooming",
        "category_sort_order" to "Display Order",
        "uncategorized_label" to "Uncategorized Services",
        "btn_add_service" to "+ Add Service",
        "edit_service_title" to "Edit Service",
        "new_service_title" to "Add New Service",
        "service_name_label" to "Service Name",
        "service_category_dropdown" to "Select Category",
        "service_price_label" to "Price (₹)",
        "service_duration_label" to "Service Duration",
        "service_duration_fixed_note" to "Fixed duration dropdown required by booking system",
        "service_buffer_label" to "Buffer Time After Service",
        "service_buffer_hint" to "Post-service cleaning & prep time before next booking",
        "assign_stylists_title" to "Assign Stylists",
        "assign_stylists_desc" to "Which stylists can perform this service?",
        "select_all_staff" to "Select All Staff",
        "btn_save_service" to "Save Service",
        "service_saved_success" to "Service catalog updated successfully!",
        "delete_service_confirm" to "Delete this service from catalog?",
        "delete_category_confirm" to "Delete category? Services will move to Uncategorized.",

        // Part 4: Combos / Packages
        "combos_title" to "Combos & Package Deals",
        "btn_add_combo" to "+ Add Combo Package",
        "combo_name_label" to "Combo Name",
        "combo_name_hint" to "e.g. Groom Special, Total Glow, Bridal Spa",
        "combo_price_label" to "Package Price (₹)",
        "select_services_for_combo" to "Select Included Services",
        "combo_total_time" to "Total Duration:",
        "combo_time_calc" to "Summed duration from included services",
        "combo_saved_success" to "Combo package saved successfully!",
        "delete_combo_confirm" to "Delete this combo package?",

        // Part 4: Staff Management
        "staff_list_title" to "Staff & Team Members",
        "btn_add_staff" to "+ Add Stylist / Staff",
        "staff_name_label" to "Stylist Full Name",
        "staff_commission_label" to "Commission Rate (%)",
        "staff_commission_hint" to "0% to 100% of service bill",
        "staff_hours_title" to "Working Hours & Days",
        "staff_services_title" to "Services Performed",
        "staff_working_toggle" to "Working this day",
        "staff_off_day" to "Weekly Off",
        "btn_save_staff_hours" to "Save Working Hours",
        "btn_save_staff_services" to "Save Assigned Services",
        "staff_saved_success" to "Staff member saved successfully!",

        // Part 4: Working Hours (Salon-level)
        "salon_hours_title" to "Salon Operating Hours",
        "salon_hours_desc" to "Set opening and closing timings for each day of the week.",
        "salon_hours_rule_note" to "A stylist's slots are limited to both the salon's hours AND their own working hours — whichever is shorter.",
        "open_label" to "Open",
        "closed_label" to "Closed",
        "open_time_label" to "Open Time",
        "close_time_label" to "Close Time",
        "btn_save_salon_hours" to "Save Salon Operating Hours",

        // Part 4: Booking Settings
        "settings_title" to "Booking & Appointment Settings",
        "slot_interval_label" to "Slot Interval",
        "slot_interval_desc" to "How far apart booking start times are shown to customers (e.g. 10:00, 10:30, 11:00)",
        "booking_window_label" to "Booking Window (Days Ahead)",
        "booking_window_desc" to "How many days ahead customers can view slots and make reservations",
        "min_notice_label" to "Minimum Advance Notice",
        "min_notice_desc" to "Minimum time before a booking can start to prevent unexpected sudden arrivals",
        "zero_wait_title" to "Zero-Wait Promise & Late Arrival Credit",
        "late_threshold_label" to "Salon Delay Threshold",
        "late_threshold_desc" to "Notify/credit customer if salon is late by more than this many minutes",
        "late_credit_label" to "Late Credit Amount (₹)",
        "late_credit_desc" to "If enabled, a customer who arrived on time gets an automatic account credit when their service starts later than this. Set ₹0 to disable.",
        "btn_save_settings" to "Save Booking Settings",

        // Part 4: Payout Details
        "payout_title" to "Payout & Banking Details",
        "payout_notice" to "This is only used when online payments/deposits are enabled — not required yet.",
        "holder_name_label" to "Account Holder Name",
        "upi_id_label" to "UPI ID (VPA)",
        "upi_id_hint" to "e.g. salonname@okhdfcbank",
        "bank_acc_label" to "Bank Account Number",
        "bank_ifsc_label" to "Bank IFSC Code",
        "btn_save_payout" to "Save Payout Details",
        "payout_saved_success" to "Payout details saved securely!",

        // Part 5: Earnings (Kamai)
        "earnings_title" to "Kamai & Stylist Earnings",
        "earnings_subtitle" to "Real-time revenue, bookings & commission calculation",
        "date_range_today" to "Today",
        "date_range_week" to "This Week",
        "date_range_month" to "This Month",
        "date_range_custom" to "Custom Range",
        "earnings_total_revenue" to "Total Revenue",
        "earnings_completed_bookings" to "Completed Bookings",
        "earnings_no_shows" to "No-Shows",
        "earnings_total_commission" to "Total Commission Owed",
        "earnings_stylist_breakdown" to "Per-Stylist Performance & Commission",
        "earnings_empty" to "No earnings recorded for this date range.",
        "stylist_revenue" to "Revenue",
        "stylist_completed" to "Completed",
        "stylist_commission" to "Commission",
        "stylist_owed" to "Owed",
        "stylist_no_shows" to "No-Shows",
        "stylist_cancellations" to "Cancelled",
        "revenue_chart_title" to "Revenue by Stylist (₹)",
        "from_date_label" to "From Date (YYYY-MM-DD)",
        "to_date_label" to "To Date (YYYY-MM-DD)",
        "apply_custom_range" to "Apply Date Filter",

        // Part 5: Reviews
        "section_reviews" to "Reviews & Ratings",
        "section_reviews_desc" to "Customer feedback, ratings and owner replies",
        "reviews_title" to "Salon Reviews & Feedback",
        "reviews_avg_rating" to "Average Rating",
        "reviews_count" to "Total Reviews",
        "review_reply_label" to "Owner Response",
        "btn_reply" to "Reply to Customer",
        "reply_dialog_title" to "Reply to Customer Review",
        "reply_input_placeholder" to "Write a professional, warm reply...",
        "btn_submit_reply" to "Post Public Reply",
        "btn_cancel" to "Cancel",
        "reviews_empty" to "No reviews yet. Completed bookings will appear here once customers leave feedback.",
        "reply_pending_badge" to "Pending Reply",

        // Part 5: Notifications
        "notifications_title" to "Notifications",
        "notifications_empty" to "No notifications yet",
        "mark_all_read" to "Mark All as Read",
        "notif_type_new_booking" to "New Booking",
        "notif_type_delay_alert" to "Zero-Wait Delay Alert",
        "notif_type_reminder" to "Reminder",
        "notif_type_salon_approved" to "Salon Approved",
        "notif_type_late_credit" to "Late Arrival Credit",

        // Part 5: Profile & Settings Modal
        "profile_title" to "Owner Profile & Settings",
        "owner_info" to "Owner Account",
        "app_language" to "App Language / भाषा",
        "connected_salon" to "Salon Information",
        "system_status" to "System Connection",
        "sync_live" to "Realtime Sync Active",
        "btn_logout" to "Sign Out / Logout",
        "confirm_logout" to "Are you sure you want to sign out?",
        "offline_retry" to "Retry Loading"
    )


    private val hindiStrings = mapOf(
        // Salon settings screens
        "account_holder_label" to "खाताधारक का नाम",
        "active" to "चालू",
        "add_category_title" to "कैटेगरी जोड़ें",
        "add_combo_title" to "पैकेज जोड़ें",
        "add_service_title" to "सर्विस जोड़ें",
        "add_staff_title" to "स्टाइलिस्ट जोड़ें",
        "all_staff_assigned" to "सभी स्टाइलिस्ट",
        "assign_staff_title" to "यह सर्विस कौन करता है",
        "booking_settings_subtitle" to "ग्राहक कैसे बुक करें, यह तय करें",
        "booking_settings_title" to "बुकिंग सेटिंग्स",
        "booking_window_hint" to "ग्राहक कितने दिन पहले तक बुक कर सकते हैं (अधिकतम 30)",
        "btn_save" to "सेव करें",
        "cancel" to "रद्द करें",
        "categories_count" to "कैटेगरी",
        "categories_title" to "कैटेगरी",
        "category_sort_order_label" to "दिखाने का क्रम",
        "combo_total_duration" to "कुल समय",
        "combos_subtitle" to "सर्विस को खास दाम पर जोड़ें",
        "delete" to "हटाएं",
        "edit_category_title" to "कैटेगरी बदलें",
        "edit_combo_title" to "पैकेज बदलें",
        "ifsc_label" to "बैंक IFSC कोड",
        "inactive" to "बंद",
        "manage_staff_hours_services" to "काम के घंटे और सर्विस",
        "min_notice_hint" to "बुकिंग और अपॉइंटमेंट के बीच कम से कम समय",
        "minutes_abbr" to "मिनट",
        "payout_subtitle" to "आपकी कमाई कहाँ भेजी जाए",
        "save" to "सेव करें",
        "save_booking_settings" to "बुकिंग सेटिंग्स सेव करें",
        "save_payout_details" to "पेमेंट जानकारी सेव करें",
        "save_salon_hours" to "सैलून का समय सेव करें",
        "save_staff_hours" to "काम के घंटे सेव करें",
        "save_staff_services" to "सर्विस सेव करें",
        "section_booking_settings" to "बुकिंग सेटिंग्स",
        "section_booking_settings_desc" to "स्लॉट गैप, एडवांस बुकिंग, देरी नियम",
        "section_combos" to "पैकेज",
        "section_combos_desc" to "सर्विस मिलाकर ऑफर बनाएं",
        "section_payout_details" to "पेमेंट जानकारी",
        "section_payout_details_desc" to "पेमेंट के लिए UPI या बैंक खाता",
        "section_salon_profile" to "सैलून प्रोफ़ाइल",
        "section_salon_profile_desc" to "नाम, पता, फोटो",
        "section_services" to "सर्विस",
        "section_services_desc" to "सर्विस, दाम और समय",
        "section_staff" to "स्टाफ",
        "section_staff_desc" to "स्टाइलिस्ट, घंटे और कमीशन",
        "section_time_off" to "ब्रेक और छुट्टी",
        "section_time_off_desc" to "लंच ब्रेक, छुट्टियाँ और स्टाफ की छुट्टी",
        "section_working_hours" to "काम के घंटे",
        "section_working_hours_desc" to "हर दिन खुलने और बंद होने का समय",
        "service_duration_hint" to "सर्विस में कितना समय लगता है (ग्राहक को इसी हिसाब से स्लॉट दिखेंगे)",
        "services_catalog_title" to "सर्विस",
        "services_count" to "सर्विस",
        "slot_interval_hint" to "ग्राहक को दिखने वाले शुरू होने के समय के बीच का गैप। स्टाइलिस्ट खाली होते ही भी स्लॉट मिलता है।",
        "staff_assigned_count" to "स्टाइलिस्ट",
        "staff_commission_suffix" to "कमीशन",
        "staff_members_count" to "स्टाइलिस्ट",
        "staff_tab_hours" to "काम के घंटे",
        "staff_tab_services" to "सर्विस",
        "staff_title" to "स्टाफ",
        "working_hours_subtitle" to "ग्राहक केवल इन घंटों में बुक कर सकते हैं",
        "working_hours_title" to "सैलून के काम के घंटे",
        "zero_wait_desc" to "देरी होने पर ग्राहक को अपने-आप सूचना मिलती है, और तय सीमा से ज़्यादा देरी पर क्रेडिट मिलता है।",
        "app_title" to "सैलून ओनर",
        "login_title" to "सैलून ओनर लॉगिन",
        "login_subtitle" to "अपने सैलून, बुकिंग्स और स्टाफ का प्रबंधन करने के लिए साइन इन करें",
        "email_label" to "ईमेल पता",
        "email_placeholder" to "name@example.com",
        "password_label" to "पासवर्ड",
        "confirm_password_label" to "पासवर्ड की पुष्टि करें",
        "login_btn" to "लॉगिन करें",
        "signup_btn" to "खाता बनाएं",
        "need_account" to "खाता नहीं है? साइन अप करें",
        "have_account" to "पहले से खाता है? लॉगिन करें",
        "signup_title" to "सैलून ओनर के रूप में रजिस्टर करें",
        "signup_subtitle" to "अपना सैलून शुरू करने के लिए अकाउंट बनाएं",

        // Steps
        "step_owner" to "मालिक का विवरण",
        "step_salon" to "सैलून का विवरण",
        "step_verify" to "सत्यापन",
        "step_1_of_3" to "चरण 1 / 3",
        "step_2_of_3" to "चरण 2 / 3",
        "step_3_of_3" to "चरण 3 / 3",

        // Step 1
        "owner_name_label" to "मालिक का पूरा नाम",
        "owner_name_hint" to "अपना पूरा नाम दर्ज करें",
        "language_preference" to "पसंदीदा भाषा",
        "language_english" to "English",
        "language_hindi" to "हिंदी (Hindi)",
        "next_btn" to "आगे बढ़ें",
        "back_btn" to "पीछे जाएं",

        // Step 2
        "salon_name_label" to "सैलून का नाम",
        "salon_name_hint" to "उदा. लुक्स यूनिसेक्स सैलून",
        "salon_type_label" to "सैलून का प्रकार",
        "type_men" to "पुरुष (Men)",
        "type_women" to "महिला (Women)",
        "type_unisex" to "यूनिसेक्स (Unisex)",
        "address_label" to "पूरा पता",
        "address_hint" to "दुकान / भवन / सड़क का पता",
        "area_label" to "क्षेत्र / इलाका",
        "area_hint" to "उदा. एमजी रोड, मुख्य बाजार",
        "city_label" to "शहर",
        "city_hint" to "उदा. मुंबई, दिल्ली, जयपुर",
        "pincode_label" to "पिनकोड",
        "pincode_hint" to "6 अंकों का पिनकोड (उदा. 400050)",
        "phone_label" to "सैलून संपर्क फोन",
        "phone_hint" to "10 अंकों का मोबाइल नंबर",
        "location_header" to "मानचित्र स्थान (वैकल्पिक)",
        "use_my_location" to "वर्तमान स्थान का उपयोग करें",
        "lat_label" to "अक्षांश (Latitude)",
        "lng_label" to "देशांतर (Longitude)",
        "gst_label" to "जीएसटी नंबर (वैकल्पिक)",
        "gst_hint" to "15 अंकों का GSTIN नंबर",

        // Step 3
        "verify_header" to "दस्तावेज़ सत्यापन",
        "verify_sub" to "कम से कम एक वैध व्यापार या पहचान दस्तावेज़ अपलोड करें (अधिकतम 5MB)",
        "doc_type_label" to "दस्तावेज़ का प्रकार",
        "doc_gst" to "जीएसटी प्रमाण पत्र",
        "doc_shop_license" to "शॉप एवं स्थापना लाइसेंस",
        "doc_visiting_card" to "विजिटिंग कार्ड",
        "doc_id_proof" to "मालिक का आईडी प्रूफ (आधार / पैन)",
        "doc_other" to "अन्य आधिकारिक दस्तावेज़",
        "select_file" to "दस्तावेज़ चुनें (फोटो या PDF)",
        "file_selected" to "चुनी गई फाइल:",
        "terms_checkbox" to "मैं नियम व शर्तों को स्वीकार करता हूँ और पुष्टि करता हूँ कि सभी विवरण सही हैं।",
        "submit_verification" to "सत्यापन के लिए जमा करें",

        // Pending & Rejected
        "pending_title" to "सैलून समीक्षाधीन है",
        "pending_desc" to "आपका सैलून समीक्षाधीन है। स्वीकृति मिलने पर हम आपको सूचित करेंगे।",
        "refresh_status" to "स्थिति ताज़ा करें",
        "rejected_title" to "आवेदन अस्वीकृत",
        "rejection_reason_label" to "अस्वीकृति का कारण:",
        "edit_resubmit" to "संशोधित करें और पुनः भेजें",
        "sign_out" to "साइन आउट करें",

        // Part 2: 4 Bottom Tabs
        "tab_today" to "आज (Aaj)",
        "tab_bookings" to "बुकिंग्स (Bookings)",
        "tab_salon" to "सैलून (Salon)",
        "tab_earnings" to "कमाई (Kamai)",

        // Dashboard Stats
        "stat_today_bookings" to "आज की कुल बुकिंग",
        "stat_completed" to "पूर्ण",
        "stat_upcoming" to "आगामी",
        "stat_revenue" to "कमाई",
        "stat_no_shows" to "अनुपस्थित",
        "stat_pending_replies" to "लंबित समीक्षा उत्तर",
        "salon_off_banner" to "आपका सैलून अभी ग्राहकों के लिए बंद है",
        "salon_is_active_online" to "सैलून खुला है और बुकिंग स्वीकार कर रहा है",
        "salon_turn_on" to "चालू करें",
        "salon_turn_off" to "बंद करें",
        "btn_add_walkin" to "+ वॉक-इन जोड़ें",
        "btn_view_schedule" to "आज का शेड्यूल देखें",
        "quick_actions" to "त्वरित कार्य",
        "dashboard_title" to "आज का विवरण",
        "live_sync_active" to "लाइव रियल-टाइम सिंक",

        // Today's Schedule
        "schedule_title" to "आज का शेड्यूल",
        "all_stylists" to "सभी स्टाइलिस्ट",
        "btn_arrived" to "आ गए",
        "btn_cancel" to "रद्द करें",
        "btn_noshow" to "अनुपस्थित (No-show)",
        "btn_start_service" to "सेवा शुरू करें",
        "btn_mark_done" to "पूर्ण मार्क करें",
        "empty_bookings" to "आज कोई बुकिंग नहीं है",
        "empty_bookings_desc" to "आज के लिए अभी कोई बुकिंग निर्धारित नहीं है।",
        "status_confirmed" to "पुष्टि की गई",
        "status_arrived" to "आ गए",
        "status_in_service" to "सेवा जारी है",
        "status_completed" to "पूर्ण",
        "status_cancelled" to "रद्द",
        "status_no_show" to "अनुपस्थित",
        "source_walkin" to "वॉक-इन",
        "source_online" to "ऑनलाइन",
        "tap_to_call" to "ग्राहक को कॉल करें",

        // Walk-in Modal
        "modal_walkin_title" to "वॉक-इन ग्राहक जोड़ें",
        "modal_walkin_sub" to "वॉक-इन ग्राहक के लिए तुरंत स्लॉट बुक करें",
        "field_stylist" to "स्टाइलिस्ट चुनें",
        "field_service" to "सेवा चुनें",
        "field_customer_name" to "ग्राहक का नाम",
        "field_customer_name_hint" to "ग्राहक का नाम दर्ज करें",
        "field_customer_phone" to "फोन नंबर (वैकल्पिक)",
        "field_customer_phone_hint" to "10 अंकों का मोबाइल नंबर",
        "btn_create_walkin" to "बुकिंग दर्ज करें",
        "btn_close" to "बंद करें",

        // Notifications
        "notifications_title" to "सूचनाएं",
        "no_notifications" to "कोई नई सूचना नहीं है",

        // Legacy / Shared
        "verified_badge" to "सत्यापित पार्टनर",
        "status_approved" to "स्वीकृत",
        "hours_note" to "कार्य समय: सुबह 10:00 से रात 8:00 तक (सातों दिन)",

        // Part 3: Bookings List, Customer History, Reschedule & Time Off
        "subtab_upcoming" to "आगामी (Upcoming)",
        "subtab_past" to "पिछली (Past)",
        "header_today" to "आज",
        "header_tomorrow" to "कल",
        "booking_details_title" to "बुकिंग विवरण",
        "btn_call_customer" to "ग्राहक को कॉल करें",
        "btn_whatsapp_customer" to "व्हाट्सएप संदेश भेजें",
        "btn_view_history" to "ग्राहक का इतिहास देखें",
        "btn_reschedule" to "समय बदलें (Reschedule)",
        "btn_cancel_booking" to "बुकिंग रद्द करें",
        "reschedule_dialog_title" to "बुकिंग का समय बदलें",
        "select_new_date" to "नई तिथि चुनें",
        "select_new_time" to "नया समय स्लॉट चुनें",
        "time_slot_busy" to "इस समय स्टाइलिस्ट व्यस्त हैं",
        "confirm_reschedule_btn" to "नया समय सुनिश्चित करें",
        "cancel_booking_confirm_title" to "बुकिंग रद्द करें?",
        "cancel_booking_confirm_desc" to "क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं? ग्राहक को सूचित कर दिया जाएगा।",
        "confirm_cancel_action" to "हाँ, रद्द करें",
        "customer_history_title" to "ग्राहक का इतिहास",
        "customer_total_visits" to "कुल विज़िट",
        "customer_no_shows" to "अनुपस्थितियां",
        "customer_total_spent" to "कुल खर्च",
        "customer_last_visit" to "अंतिम विज़िट",
        "badge_regular" to "नियमित ग्राहक",
        "badge_attention" to "अक्सर अनुपस्थित रहने वाले",
        "badge_new" to "नए ग्राहक",
        "empty_upcoming" to "कोई आगामी बुकिंग नहीं है",
        "empty_upcoming_desc" to "इस समय सीमा में कोई पुष्ट या सक्रिय आगामी बुकिंग नहीं है।",
        "empty_past" to "कोई पिछली बुकिंग नहीं है",
        "empty_past_desc" to "इस अवधि में कोई पूर्ण, रद्द या अनुपस्थित बुकिंग नहीं है।",
        "time_off_section_title" to "स्टाफ छुट्टियां व सैलून ब्रेक",
        "recurring_breaks_title" to "दैनिक व आवर्ती ब्रेक",
        "staff_time_off_title" to "स्टाफ अवकाश व सैलून छुट्टियां",
        "btn_add_break" to "+ आवर्ती ब्रेक जोड़ें",
        "btn_add_time_off" to "+ छुट्टी / अवकाश जोड़ें",
        "field_break_label" to "ब्रेक का नाम (उदा. लंच ब्रेक)",
        "field_leave_reason" to "कारण / विवरण (वैकल्पिक)",
        "field_day_of_week" to "सप्ताह का दिन",
        "day_everyday" to "प्रतिदिन (Every Day)",
        "whole_salon_option" to "पूरा सैलून (सभी स्टाफ)",
        "conflicts_dialog_title" to "शेड्यूल टकराव पाया गया",
        "conflicts_dialog_desc" to "इस छुट्टी के समय पहले से पुष्ट बुकिंग्स मौजूद हैं। आगे बढ़ने पर वे स्वतः रद्द होकर ग्राहकों को सूचित किया जाएगा:",
        "btn_cancel_and_proceed" to "बुकिंग्स रद्द करें व छुट्टी दर्ज करें",
        "delete_confirm_title" to "प्रविष्टि हटाएं?",
        "delete_confirm_desc" to "क्या आप वाकई इस ब्रेक या छुट्टी की प्रविष्टि को हटाना चाहते हैं?",
        "btn_delete" to "हटाएं",

        // Errors & Validation
        "err_fill_all" to "कृपया सभी आवश्यक फ़ील्ड भरें",
        "err_pincode" to "पिनकोड 1-9 से शुरू होने वाला 6 अंकों का होना चाहिए",
        "err_phone" to "कृपया एक मान्य फोन नंबर दर्ज करें",
        "err_terms" to "कृपया नियम और शर्तें स्वीकार करें",
        "err_no_doc" to "कृपया कम से कम एक दस्तावेज़ अपलोड करें",
        "err_pass_match" to "पासवर्ड मेल नहीं खाते",
        "err_pass_short" to "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",

        // Part 4: Salon Management Sections
        "salon_menu_title" to "सैलून प्रबंधन",
        "salon_menu_subtitle" to "अपनी प्रोफाइल, सेवाएं, स्टाफ, समय और सेटिंग्स प्रबंधित करें",
        "menu_salon_profile" to "सैलून प्रोफाइल",
        "desc_salon_profile" to "नाम, पता, तस्वीरें, संपर्क और चालू स्थिति",
        "menu_services_categories" to "सेवाएं और श्रेणियां",
        "desc_services_categories" to "सेवा कैटलॉग, मूल्य, निश्चित समय और स्टाफ",
        "menu_combos_packages" to "कॉम्बो और पैकेज",
        "desc_combos_packages" to "विशेष मूल्य के साथ बंडल सेवाएं",
        "menu_staff" to "स्टाफ और स्टाइलिस्ट",
        "desc_staff" to "स्टाइलिस्ट, कमीशन दरें, कार्य समय और सेवाएं",
        "menu_working_hours" to "सैलून कार्य समय",
        "desc_working_hours" to "साप्ताहिक खुलने और बंद होने का समय",
        "menu_time_off" to "छुट्टियां और ब्रेक",
        "desc_time_off" to "स्टाफ छुट्टियां, अवकाश और दैनिक सैलून ब्रेक",
        "menu_booking_settings" to "बुकिंग सेटिंग्स",
        "desc_booking_settings" to "स्लॉट अंतराल, अग्रिम बुकिंग और लेट क्रेडिट",
        "menu_payout_details" to "भुगतान विवरण",
        "desc_payout_details" to "ऑनलाइन सेटलमेंट के लिए बैंक खाता और यूपीआई",

        // Part 4: Profile Section
        "profile_edit_title" to "सैलून प्रोफाइल संपादित करें",
        "profile_description_label" to "सैलून का विवरण",
        "profile_description_hint" to "ग्राहकों को अपने सैलून, सेवाओं और माहौल के बारे में बताएं",
        "profile_photos_title" to "सैलून की तस्वीरें",
        "profile_photos_desc" to "सैलून की तस्वीरें अपलोड करें और एक मुख्य कवर फोटो चुनें।",
        "btn_add_photo" to "+ तस्वीर जोड़ें",
        "badge_cover_photo" to "मुख्य कवर",
        "btn_set_cover" to "कवर बनाएं",
        "btn_remove_photo" to "हटाएं",
        "salon_status_toggle" to "बुकिंग स्वीकार करें (सैलून चालू)",
        "salon_status_toggle_desc" to "बंद होने पर ग्राहकों को आपका सैलून नहीं दिखेगा और बुकिंग नहीं होगी।",
        "verified_partner_badge" to "सत्यापित पार्टनर",
        "under_review_badge" to "सत्यापन प्रक्रियाधीन",
        "rating_label" to "रेटिंग",
        "reviews_count" to "समीक्षाएं",
        "btn_save_profile" to "प्रोफाइल परिवर्तन सहेजें",
        "profile_saved_success" to "सैलून प्रोफाइल सफलतापूर्वक अपडेट हो गई!",

        // Part 4: Services & Categories
        "categories_header" to "सेवा श्रेणियां",
        "btn_add_category" to "+ श्रेणी जोड़ें",
        "category_name_label" to "श्रेणी का नाम",
        "category_name_hint" to "उदा. हेयरकट, स्किन व स्पा, ग्रूमिंग",
        "category_sort_order" to "प्रदर्शन क्रम",
        "uncategorized_label" to "बिना श्रेणी की सेवाएं",
        "btn_add_service" to "+ सेवा जोड़ें",
        "edit_service_title" to "सेवा संपादित करें",
        "new_service_title" to "नई सेवा जोड़ें",
        "service_name_label" to "सेवा का नाम",
        "service_category_dropdown" to "श्रेणी चुनें",
        "service_price_label" to "मूल्य (₹)",
        "service_duration_label" to "सेवा का समय",
        "service_duration_fixed_note" to "डेटाबेस के लिए निश्चित समय अवधि आवश्यक",
        "service_buffer_label" to "सेवा के बाद बफर समय",
        "service_buffer_hint" to "अगले ग्राहक से पहले सफाई व तैयारी का समय",
        "assign_stylists_title" to "स्टाइलिस्ट असाइन करें",
        "assign_stylists_desc" to "यह सेवा कौन प्रदान कर सकता है?",
        "select_all_staff" to "सभी स्टाफ चुनें",
        "btn_save_service" to "सेवा सहेजें",
        "service_saved_success" to "सेवा कैटलॉग सफलतापूर्वक अपडेट हुआ!",
        "delete_service_confirm" to "क्या आप इस सेवा को हटाना चाहते हैं?",
        "delete_category_confirm" to "श्रेणी हटाएं? इसके अंतर्गत सेवाएं बिना श्रेणी की हो जाएंगी।",

        // Part 4: Combos / Packages
        "combos_title" to "कॉम्बो और पैकेज डील",
        "btn_add_combo" to "+ कॉम्बो डील जोड़ें",
        "combo_name_label" to "कॉम्बो का नाम",
        "combo_name_hint" to "उदा. ग्रूम स्पेशल, ब्राइडल ग्लो",
        "combo_price_label" to "पैकेज मूल्य (₹)",
        "select_services_for_combo" to "शामिल सेवाएं चुनें",
        "combo_total_time" to "कुल समय:",
        "combo_time_calc" to "शामिल सेवाओं से आकलित समय",
        "combo_saved_success" to "कॉम्बो पैकेज सहेजा गया!",
        "delete_combo_confirm" to "क्या आप इस कॉम्बो पैकेज को हटाना चाहते हैं?",

        // Part 4: Staff Management
        "staff_list_title" to "स्टाफ और टीम के सदस्य",
        "btn_add_staff" to "+ स्टाइलिस्ट / स्टाफ जोड़ें",
        "staff_name_label" to "स्टाइलिस्ट का पूरा नाम",
        "staff_commission_label" to "कमीशन दर (%)",
        "staff_commission_hint" to "बिल राशि का 0% से 100%",
        "staff_hours_title" to "कार्य समय और दिन",
        "staff_services_title" to "प्रदान की जाने वाली सेवाएं",
        "staff_working_toggle" to "इस दिन कार्य करेंगे",
        "staff_off_day" to "साप्ताहिक अवकाश",
        "btn_save_staff_hours" to "कार्य समय सहेजें",
        "btn_save_staff_services" to "असाइन की गई सेवाएं सहेजें",
        "staff_saved_success" to "स्टाफ विवरण सफलतापूर्वक अपडेट हो गया!",

        // Part 4: Working Hours (Salon-level)
        "salon_hours_title" to "सैलून संचालन का समय",
        "salon_hours_desc" to "सप्ताह के प्रत्येक दिन के लिए खुलने और बंद होने का समय निर्धारित करें।",
        "salon_hours_rule_note" to "स्टाइलिस्ट के स्लॉट सैलून के समय और उनके स्वयं के कार्य समय दोनों तक सीमित होते हैं — जो भी कम हो।",
        "open_label" to "खुला",
        "closed_label" to "बंद",
        "open_time_label" to "खुलने का समय",
        "close_time_label" to "बंद होने का समय",
        "btn_save_salon_hours" to "सैलून समय सहेजें",

        // Part 4: Booking Settings
        "settings_title" to "बुकिंग और अपॉइंटमेंट सेटिंग्स",
        "slot_interval_label" to "स्लॉट अंतराल",
        "slot_interval_desc" to "ग्राहकों को दिखाए जाने वाले बुकिंग समय में अंतर (उदा. 10:00, 10:30, 11:00)",
        "booking_window_label" to "अग्रिम बुकिंग विंडो (दिन)",
        "booking_window_desc" to "ग्राहक कितने दिन आगे तक स्लॉट देखकर अग्रिम बुकिंग कर सकते हैं",
        "min_notice_label" to "न्यूनतम अग्रिम नोटिस समय",
        "min_notice_desc" to "अचानक आने वाले ग्राहकों से बचने के लिए सेवा शुरू होने से पहले आवश्यक न्यूनतम समय",
        "zero_wait_title" to "ज़ीरो-वेट प्रॉमिस और लेट अराइवल क्रेडिट",
        "late_threshold_label" to "सैलून देरी सीमा",
        "late_threshold_desc" to "यदि सैलून इससे अधिक मिनट लेट होता है तो ग्राहक को सूचित/क्रेडिट करें",
        "late_credit_label" to "लेट क्रेडिट राशि (₹)",
        "late_credit_desc" to "सक्रिय होने पर, समय पर आए ग्राहक को सेवा में देरी होने पर स्वतः क्रेडिट मिलता है। निष्क्रिय करने के लिए ₹0 रखें।",
        "btn_save_settings" to "बुकिंग सेटिंग्स सहेजें",

        // Part 4: Payout Details
        "payout_title" to "भुगतान और बैंक विवरण",
        "payout_notice" to "यह केवल ऑनलाइन भुगतान/जमा राशि सक्षम होने पर उपयोग किया जाता है — अभी अनिवार्य नहीं है।",
        "holder_name_label" to "खाता धारक का नाम",
        "upi_id_label" to "यूपीआई आईडी (VPA)",
        "upi_id_hint" to "उदा. salonname@okhdfcbank",
        "bank_acc_label" to "बैंक खाता संख्या",
        "bank_ifsc_label" to "बैंक IFSC कोड",
        "btn_save_payout" to "भुगतान विवरण सहेजें",
        "payout_saved_success" to "भुगतान विवरण सुरक्षित रूप से सहेजा गया!",

        // Part 5: Earnings (Kamai)
        "earnings_title" to "कमाई और स्टाइलिस्ट विवरण",
        "earnings_subtitle" to "रीयल-टाइम राजस्व, पूर्ण बुकिंग और कमीशन गणना",
        "date_range_today" to "आज",
        "date_range_week" to "इस सप्ताह",
        "date_range_month" to "इस महीने",
        "date_range_custom" to "कस्टम तिथि",
        "earnings_total_revenue" to "कुल राजस्व",
        "earnings_completed_bookings" to "पूर्ण बुकिंग्स",
        "earnings_no_shows" to "नो-शो",
        "earnings_total_commission" to "कुल देय कमीशन",
        "earnings_stylist_breakdown" to "स्टाइलिस्ट प्रदर्शन और कमीशन",
        "earnings_empty" to "चयनित तिथि सीमा के लिए कोई कमाई दर्ज नहीं है।",
        "stylist_revenue" to "राजस्व",
        "stylist_completed" to "पूर्ण",
        "stylist_commission" to "कमीशन",
        "stylist_owed" to "देय राशि",
        "stylist_no_shows" to "नो-शो",
        "stylist_cancellations" to "रद्द",
        "revenue_chart_title" to "स्टाइलिस्ट अनुसार राजस्व (₹)",
        "from_date_label" to "प्रारंभ तिथि (YYYY-MM-DD)",
        "to_date_label" to "अंतिम तिथि (YYYY-MM-DD)",
        "apply_custom_range" to "तिथि फ़िल्टर लागू करें",

        // Part 5: Reviews
        "section_reviews" to "समीक्षाएं और रेटिंग",
        "section_reviews_desc" to "ग्राहकों की प्रतिक्रिया, रेटिंग और ओनर के उत्तर",
        "reviews_title" to "सैलून समीक्षाएं और फीडबैक",
        "reviews_avg_rating" to "औसत रेटिंग",
        "reviews_count" to "कुल समीक्षाएं",
        "review_reply_label" to "ओनर का उत्तर",
        "btn_reply" to "ग्राहक को उत्तर दें",
        "reply_dialog_title" to "समीक्षा का उत्तर लिखें",
        "reply_input_placeholder" to "ग्राहक को विनम्र और उपयोगी उत्तर लिखें...",
        "btn_submit_reply" to "उत्तर पोस्ट करें",
        "btn_cancel" to "रद्द करें",
        "reviews_empty" to "अभी तक कोई समीक्षा नहीं है। ग्राहक फीडबैक देने पर यहां प्रदर्शित होगी।",
        "reply_pending_badge" to "उत्तर लंबित",

        // Part 5: Notifications
        "notifications_title" to "सूचनाएं",
        "notifications_empty" to "कोई नई सूचना नहीं है",
        "mark_all_read" to "सभी को पढ़ा हुआ मार्क करें",
        "notif_type_new_booking" to "नई बुकिंग",
        "notif_type_delay_alert" to "ज़ीरो-वेट देरी अलर्ट",
        "notif_type_reminder" to "रिमाइंडर",
        "notif_type_salon_approved" to "सैलून स्वीकृत",
        "notif_type_late_credit" to "देरी क्रेडिट",

        // Part 5: Profile & Settings Modal
        "profile_title" to "ओनर प्रोफ़ाइल और सेटिंग्स",
        "owner_info" to "ओनर खाता",
        "app_language" to "ऐप भाषा / App Language",
        "connected_salon" to "सैलून जानकारी",
        "system_status" to "सिस्टम कनेक्शन",
        "sync_live" to "रीयल-टाइम सिंक सक्रिय",
        "btn_logout" to "लॉगआउट / साइन आउट",
        "confirm_logout" to "क्या आप निश्चित रूप से लॉगआउट करना चाहते हैं?",
        "offline_retry" to "पुनः प्रयास करें"
    )

}
